modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/another-changed"
logoFile = "logo.png"
authors = "${mod_authors}"
description = '''${mod_description}'''
[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neo_version_range}"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.${mod_id}]]
    modId="smartbrainlib"
    type = "required"
    versionRange = "[1.8,)"
    ordering = "NONE"
    side = "SERVER"
[[accessTransformers]]
    file = "accesstransformer.cfg"